### Site metadata ###

site_name: EzScript
site_description: Python based HTML compiler
site_url: https://ezscript-html.github.io/

repo_url: https://github.com/ezscript-html/ezscript-html.github.io
edit_uri: edit/master/docs/docs

### Build settings ###

theme:
  name: material
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - About MkDocs: about-mkdocs.md
  - Tutorial:
      - TL;DR: tutorial/tldr.md
      - Installation: tutorial/installation.md
      - Set up project: tutorial/setup-project.md
      - Advanced: tutorial/advanced.md
      - Usage: tutorial/usage.md
      - Deploy: tutorial/deploy.md
